title: "Statistics and Cybersecurity Blog"
email: trionfetti.1991289@studenti.uniroma1.it
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog exploring the intersection of statistics and cybersecurity, featuring homework updates and insights.
baseurl: "/StatisticsBlog" # the subpath of your site, e.g. /blog
url: "https://federicotrionfetti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: FedericoTrionfetti

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed